### ISSUE TITLE
Expanded display too large

### ISSUE THREAD

**Issue by acdel123** [billthefarmer/wordlesolver#5]
The new expanded display in version 1.06 is very much too large. So much so that box to enter letters not in the puzzle gets cut off. I had to revert back to 1.05

Can the display be reverted back to the previous size, or at least make size user selectable?

**Comment by billthefarmer** [comment]
What device are you using? The display resizes to suit the size of the device screen.

![Screenshot_20230622-131603 1](https://github.com/billthefarmer/wordlesolver/assets/3448386/1fcde60a-faa3-49a7-9616-57f6c5139ddd)

![Screenshot_20230622-131608 1](https://github.com/billthefarmer/wordlesolver/assets/3448386/b2c6262c-a12c-4b91-921f-8ceef54f87c1)

**Comment by acdel123** [comment]
I am on a Tab S6 Lite 10" tablet.  

The expanded view:
![Screenshot_20230621_201429_WordleSolver](https://github.com/billthefarmer/wordlesolver/assets/106332409/5ccc485e-7902-443a-b8ed-64b4c0fb87a0)


The view was much more comfortable before:
![Screenshot_20230621_201335_WordleSolver](https://github.com/billthefarmer/wordlesolver/assets/106332409/01f43c61-db6f-4cee-96c3-57c28f3c29a3)
